import { useCallback } from 'react';
import { useI18n } from '../../runtime';

const MESSAGES = {
  'zh-CN': {
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.seconds': '秒',
    'memory.search': '搜索记忆...',
    'memory.facts': '事实',
    'memory.events': '事件',
    'memory.preferences': '偏好',
    'memory.relations': '关系',
    'memory.all': '全部',
    'memory.source': '来源',
    'memory.visibility': '可见范围',
    'memory.status': '状态',
    'memory.updatedAt': '更新时间',
    'memory.edit': '编辑',
    'memory.correct': '纠错',
    'memory.invalidate': '标记失效',
    'memory.delete': '删除',
    'memory.noResults': '暂无记忆',
    'memory.noResultsHint': '家庭记忆会随着使用逐渐积累',
    'memory.detail': '记忆详情',
    'scheduledTasks.tab': '计划任务',
    'scheduledTasks.myTasks': '我的任务',
    'scheduledTasks.familyTasks': '家庭任务',
    'scheduledTasks.newTask': '新建任务',
    'scheduledTasks.search': '搜索任务...',
    'scheduledTasks.emptyMyTasks': '你还没有计划任务',
    'scheduledTasks.emptyMyTasksHint': '现在创建一个，按你想要的时间提醒自己。',
    'scheduledTasks.emptyFamilyTasks': '这个家还没有公共计划任务',
    'scheduledTasks.emptyFamilyTasksHint': '你可以先加一个每天都会用到的提醒。',
    'scheduledTasks.loading': '正在加载任务列表...',
    'scheduledTasks.status.enabled': '已开启',
    'scheduledTasks.status.paused': '已暂停',
    'scheduledTasks.status.error': '需要处理',
    'scheduledTasks.status.invalid': '暂时无法执行',
    'scheduledTasks.trigger.schedule': '到时间自动执行',
    'scheduledTasks.trigger.heartbeat': '按间隔检查，满足条件才提醒',
    'scheduledTasks.target.plugin': '运行插件',
    'scheduledTasks.target.agent': '发送提醒',
    'scheduledTasks.target.system': '系统通知',
    'scheduledTasks.result.succeeded': '已按计划完成',
    'scheduledTasks.result.suppressed': '这次没有发出提醒',
    'scheduledTasks.result.failed': '这次没有成功，你可以稍后再试',
    'scheduledTasks.result.skipped': '跳过了这次执行',
    'scheduledTasks.result.queued': '等待执行中',
    'scheduledTasks.result.dispatching': '正在执行',
    'scheduledTasks.list.nextTime': '下次时间',
    'scheduledTasks.owner.household': '全家共享',
    'scheduledTasks.owner.member': '只提醒我',
    'scheduledTasks.detail.name': '任务名称',
    'scheduledTasks.detail.description': '任务说明',
    'scheduledTasks.detail.triggerType': '触发方式',
    'scheduledTasks.detail.nextRun': '下次执行时间',
    'scheduledTasks.detail.nextCheck': '下次检查时间',
    'scheduledTasks.detail.lastRun': '上次执行时间',
    'scheduledTasks.detail.lastResult': '最近结果',
    'scheduledTasks.detail.status': '当前状态',
    'scheduledTasks.detail.owner': '归属',
    'scheduledTasks.detail.runHistory': '运行记录',
    'scheduledTasks.action.pause': '暂停任务',
    'scheduledTasks.action.resume': '恢复任务',
    'scheduledTasks.action.edit': '编辑任务',
    'scheduledTasks.action.copy': '复制任务',
    'scheduledTasks.action.delete': '删除任务',
    'scheduledTasks.filter.all': '全部',
    'scheduledTasks.filter.enabled': '已开启',
    'scheduledTasks.filter.paused': '已暂停',
    'scheduledTasks.filter.needsAttention': '需要处理',
    'scheduledTasks.form.namePlaceholder': '给这个任务起个名字',
    'scheduledTasks.form.descriptionPlaceholder': '简单描述一下这个任务要做什么',
    'scheduledTasks.form.schedulePlaceholder': '例如：每天 09:00',
    'scheduledTasks.form.nameRequired': '请填写任务名称',
    'scheduledTasks.form.scheduleRequired': '请填写执行时间',
    'scheduledTasks.form.ownerRequired': '请选择归属成员',
    'scheduledTasks.form.ownerScope': '归属范围',
    'scheduledTasks.form.ownerMember': '归属成员',
    'scheduledTasks.form.selectMember': '请选择成员',
    'scheduledTasks.form.ownerMemberHint': '只有这个成员能看到这条提醒',
    'scheduledTasks.form.ownerHouseholdHint': '全家成员都能看到这条提醒',
    'scheduledTasks.form.scheduleType': '执行频率',
    'scheduledTasks.form.scheduleDaily': '每天固定时间',
    'scheduledTasks.form.scheduleInterval': '按间隔重复',
    'scheduledTasks.form.scheduleCron': 'Cron 表达式',
    'scheduledTasks.form.dailyTime': '执行时间',
    'scheduledTasks.form.intervalExpr': '间隔配置',
    'scheduledTasks.form.cronExpr': 'Cron 表达式',
    'scheduledTasks.form.scheduleHint': '到设定的时间就会自动执行',
    'scheduledTasks.form.heartbeatHint': '定期检查条件，满足时才提醒你',
    'scheduledTasks.form.checkInterval': '检查频率',
    'scheduledTasks.form.checkIntervalHint': '建议设置 5 分钟以上，太频繁会占用系统资源',
    'scheduledTasks.form.timezone': '时区',
    'scheduledTasks.form.targetType': '执行目标',
    'scheduledTasks.form.targetRef': '目标标识',
    'scheduledTasks.form.targetRefPlaceholder': '如插件 ID 或 Agent 编号',
    'scheduledTasks.form.enableNow': '创建后立即启用',
    'scheduledTasks.delete.title': '确认删除任务',
    'scheduledTasks.delete.message': '删除后无法恢复，确定要删除「{name}」吗？',
    'scheduledTasks.delete.confirm': '确认删除',
    'scheduledTasks.error.loadFailed': '加载任务失败，请稍后重试',
    'scheduledTasks.error.saveFailed': '保存失败，请检查设置后再试',
  },
  'en-US': {
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.seconds': 'seconds',
    'memory.search': 'Search memories...',
    'memory.facts': 'Facts',
    'memory.events': 'Events',
    'memory.preferences': 'Preferences',
    'memory.relations': 'Relations',
    'memory.all': 'All',
    'memory.source': 'Source',
    'memory.visibility': 'Visibility',
    'memory.status': 'Status',
    'memory.updatedAt': 'Updated',
    'memory.edit': 'Edit',
    'memory.correct': 'Correct',
    'memory.invalidate': 'Invalidate',
    'memory.delete': 'Delete',
    'memory.noResults': 'No memories yet',
    'memory.noResultsHint': 'Memories will accumulate over time',
    'memory.detail': 'Memory Detail',
    'scheduledTasks.tab': 'Scheduled Tasks',
    'scheduledTasks.myTasks': 'My Tasks',
    'scheduledTasks.familyTasks': 'Family Tasks',
    'scheduledTasks.newTask': 'New Task',
    'scheduledTasks.search': 'Search tasks...',
    'scheduledTasks.emptyMyTasks': 'You have no scheduled tasks yet',
    'scheduledTasks.emptyMyTasksHint': 'Create one now to remind yourself when you want.',
    'scheduledTasks.emptyFamilyTasks': 'This family has no shared tasks yet',
    'scheduledTasks.emptyFamilyTasksHint': 'You can start by adding a daily reminder everyone uses.',
    'scheduledTasks.loading': 'Loading task list...',
    'scheduledTasks.status.enabled': 'Enabled',
    'scheduledTasks.status.paused': 'Paused',
    'scheduledTasks.status.error': 'Needs Attention',
    'scheduledTasks.status.invalid': 'Temporarily Unavailable',
    'scheduledTasks.trigger.schedule': 'Runs on schedule',
    'scheduledTasks.trigger.heartbeat': 'Checks periodically, reminds when conditions met',
    'scheduledTasks.target.plugin': 'Run Plugin',
    'scheduledTasks.target.agent': 'Send Reminder',
    'scheduledTasks.target.system': 'System Notice',
    'scheduledTasks.result.succeeded': 'Completed as scheduled',
    'scheduledTasks.result.suppressed': 'No reminder was sent this time',
    'scheduledTasks.result.failed': 'This run failed, try again later',
    'scheduledTasks.result.skipped': 'Skipped this run',
    'scheduledTasks.result.queued': 'Waiting to run',
    'scheduledTasks.result.dispatching': 'Running now',
    'scheduledTasks.list.nextTime': 'Next time',
    'scheduledTasks.owner.household': 'Shared by family',
    'scheduledTasks.owner.member': 'Only remind me',
    'scheduledTasks.detail.name': 'Task Name',
    'scheduledTasks.detail.description': 'Description',
    'scheduledTasks.detail.triggerType': 'Trigger Type',
    'scheduledTasks.detail.nextRun': 'Next Run',
    'scheduledTasks.detail.nextCheck': 'Next Check',
    'scheduledTasks.detail.lastRun': 'Last Run',
    'scheduledTasks.detail.lastResult': 'Last Result',
    'scheduledTasks.detail.status': 'Status',
    'scheduledTasks.detail.owner': 'Owner',
    'scheduledTasks.detail.runHistory': 'Run History',
    'scheduledTasks.action.pause': 'Pause Task',
    'scheduledTasks.action.resume': 'Resume Task',
    'scheduledTasks.action.edit': 'Edit Task',
    'scheduledTasks.action.copy': 'Copy Task',
    'scheduledTasks.action.delete': 'Delete Task',
    'scheduledTasks.filter.all': 'All',
    'scheduledTasks.filter.enabled': 'Enabled',
    'scheduledTasks.filter.paused': 'Paused',
    'scheduledTasks.filter.needsAttention': 'Needs Attention',
    'scheduledTasks.form.namePlaceholder': 'Give this task a name',
    'scheduledTasks.form.descriptionPlaceholder': 'Describe what this task should do',
    'scheduledTasks.form.schedulePlaceholder': 'For example: every day at 09:00',
    'scheduledTasks.form.nameRequired': 'Please enter a task name',
    'scheduledTasks.form.scheduleRequired': 'Please enter a schedule',
    'scheduledTasks.form.ownerRequired': 'Please choose an owner',
    'scheduledTasks.form.ownerScope': 'Owner Scope',
    'scheduledTasks.form.ownerMember': 'Owner Member',
    'scheduledTasks.form.selectMember': 'Select a member',
    'scheduledTasks.form.ownerMemberHint': 'Only this member can see this reminder',
    'scheduledTasks.form.ownerHouseholdHint': 'All family members can see this reminder',
    'scheduledTasks.form.scheduleType': 'Schedule Type',
    'scheduledTasks.form.scheduleDaily': 'Same time every day',
    'scheduledTasks.form.scheduleInterval': 'Repeat by interval',
    'scheduledTasks.form.scheduleCron': 'Cron expression',
    'scheduledTasks.form.dailyTime': 'Run time',
    'scheduledTasks.form.intervalExpr': 'Interval expression',
    'scheduledTasks.form.cronExpr': 'Cron expression',
    'scheduledTasks.form.scheduleHint': 'Runs automatically at the configured time',
    'scheduledTasks.form.heartbeatHint': 'Checks conditions regularly and reminds only when matched',
    'scheduledTasks.form.checkInterval': 'Check interval',
    'scheduledTasks.form.checkIntervalHint': 'Five minutes or more is recommended to avoid wasting system resources',
    'scheduledTasks.form.timezone': 'Timezone',
    'scheduledTasks.form.targetType': 'Target Type',
    'scheduledTasks.form.targetRef': 'Target Reference',
    'scheduledTasks.form.targetRefPlaceholder': 'Such as a plugin ID or agent code',
    'scheduledTasks.form.enableNow': 'Enable immediately after saving',
    'scheduledTasks.delete.title': 'Confirm Delete',
    'scheduledTasks.delete.message': 'This cannot be undone. Delete "{name}"?',
    'scheduledTasks.delete.confirm': 'Delete',
    'scheduledTasks.error.loadFailed': 'Failed to load tasks. Please try again later.',
    'scheduledTasks.error.saveFailed': 'Failed to save. Check your settings and try again.',
  },
} as const;

export function useMemoriesText() {
  const { locale, t } = useI18n();

  return useCallback((key: string) => {
    const translated = t(key);
    if (translated !== key) {
      return translated;
    }
    const localeMessages = (MESSAGES[locale as keyof typeof MESSAGES] ?? MESSAGES['zh-CN']) as Record<string, string>;
    return localeMessages[key] ?? key;
  }, [locale, t]);
}
