import { FeatureParityItem } from '@familyclaw/user-core';
import { FeatureParityRegistry } from './registry';

const userWebPageParity: FeatureParityItem[] = [
  {
    feature_key: 'shared-auth-runtime',
    legacy_entry: 'apps/user-web/src/state/auth.tsx',
    new_entry: 'packages/user-core/src/state/auth.ts',
    status: 'ready',
    blocking_reason: '认证清理和账号态判断已经收口到共享层，旧前端只保留页面上下文壳。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-household-runtime',
    legacy_entry: 'apps/user-web/src/state/household.tsx',
    new_entry: 'packages/user-core/src/state/household.ts',
    status: 'ready',
    blocking_reason: '家庭摘要、持久化 key 和读写 helper 已进入共享层，旧前端通过兼容桥接消费。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-setup-runtime',
    legacy_entry: 'apps/user-web/src/state/setup.tsx',
    new_entry: 'packages/user-core/src/state/setup.ts',
    status: 'ready',
    blocking_reason: 'setup status 读取 helper 已收口到共享层，旧前端兼容层只保留最薄桥接。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-theme-preferences',
    legacy_entry: 'apps/user-web/src/theme/ThemeProvider.tsx',
    new_entry: 'packages/user-core/src/state/theme.ts',
    status: 'ready',
    blocking_reason: '主题 ID、默认值和持久化规则已共享，旧前端保留自己的视觉 token 但不再重复维护偏好规则。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-locale-preferences',
    legacy_entry: 'apps/user-web/src/i18n/localeRegistry.ts',
    new_entry: 'packages/user-core/src/state/locale.ts',
    status: 'ready',
    blocking_reason: '语言目录解析、fallback 和存储 key 已共享，旧前端保留消息字典但不再复制同一套 locale 规则。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-realtime-protocol',
    legacy_entry: 'apps/user-web/src/lib/realtime.ts',
    new_entry: 'packages/user-platform/src/realtime/index.ts',
    status: 'ready',
    blocking_reason: '实时协议校验、URL 构造和浏览器 websocket client 已进入平台适配层，旧前端只保留薄包装。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-family-settings-api',
    legacy_entry: 'apps/user-web/src/lib/api.ts',
    new_entry: 'packages/user-core/src/api/create-api-client.ts',
    status: 'ready',
    blocking_reason: '首页、家庭、设置迁移会用到的核心 API 和领域模型已经抽到共享 client，旧前端本地 API 只保留高阶能力扩展。',
    owner: 'spec011',
  },
  {
    feature_key: 'login',
    legacy_entry: 'apps/user-web/src/pages/LoginPage.tsx',
    new_entry: 'apps/user-app/src/pages/login/index.tsx',
    status: 'ready',
    blocking_reason: '旧 login 页的布局、文案、主题/语言切换和登录交互已经正式迁到 user-app，实际登录继续走共享鉴权 client 和启动摘要分流。',
    owner: 'spec011',
  },
  {
    feature_key: 'setup-wizard',
    legacy_entry: 'apps/user-web/src/pages/SetupWizardPage.tsx',
    new_entry: 'apps/user-app/src/pages/setup/index.tsx',
    status: 'ready',
    blocking_reason: '初始化向导四步已迁入 user-app：共享层已补齐 provider / route / butler bootstrap 模型与 API，页面已接入当前家庭上下文、最小 AI 主链配置、首位管家实时引导与刷新一致性。',
    owner: 'spec011',
  },
  {
    feature_key: 'home',
    legacy_entry: 'apps/user-web/src/pages/HomePage.tsx',
    new_entry: 'apps/user-app/src/pages/home/index.tsx',
    status: 'ready',
    blocking_reason: '家庭模式、指标、房间、成员、提醒与快捷入口都已落到新首页。',
    owner: 'spec011',
  },
  {
    feature_key: 'home-dashboard-shared-models',
    legacy_entry: 'apps/user-web/src/pages/HomePage.tsx',
    new_entry: 'packages/user-core/src/api/create-api-client.ts',
    status: 'ready',
    blocking_reason: '首页仪表盘依赖的 `ContextOverviewRead`、提醒总览和设备/成员/房间模型已共享，后续只差页面装配。',
    owner: 'spec011',
  },
  {
    feature_key: 'family',
    legacy_entry: 'apps/user-web/src/pages/FamilyPage.tsx',
    new_entry: 'apps/user-app/src/pages/family/index.tsx',
    status: 'ready',
    blocking_reason: '家庭资料、房间、成员和关系的核心读写链路已迁入新页面。',
    owner: 'spec011',
  },
  {
    feature_key: 'family-domain-models',
    legacy_entry: 'apps/user-web/src/pages/FamilyPage.tsx',
    new_entry: 'packages/user-core/src/domain/types.ts',
    status: 'ready',
    blocking_reason: '家庭页依赖的房间、成员、关系、偏好和上下文读模型已进入共享层。',
    owner: 'spec011',
  },
  {
    feature_key: 'assistant',
    legacy_entry: 'apps/user-web/src/pages/AssistantPage.tsx',
    new_entry: 'apps/user-app/src/pages/assistant/index.tsx',
    status: 'ready',
    blocking_reason: '助手主链已迁入 user-app：共享层已补齐 agent / 会话 / 消息 / 动作 / 建议模型与 API，页面已接入实时与 HTTP 双通道回复。',
    owner: 'spec011',
  },
  {
    feature_key: 'memories',
    legacy_entry: 'apps/user-web/src/pages/MemoriesPage.tsx',
    new_entry: 'apps/user-app/src/pages/memories/index.tsx',
    status: 'ready',
    blocking_reason: '记忆主链已迁入 user-app，列表、搜索分类、详情、纠错/失效/删除与修订历史都直接消费共享记忆模型和 API。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/index.tsx',
    status: 'ready',
    blocking_reason: '这里只代表基础偏好、运行模式、服务开关和免打扰时段已迁入 H5；AI、集成和通讯接入这些设置子入口要单独记账，不能被这一项掩盖。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-theme-language',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/index.tsx',
    status: 'ready',
    blocking_reason: '主题与语言偏好已经在新应用设置页落地，并直接使用共享偏好模型。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-ai',
    legacy_entry: 'apps/user-web/src/pages/SettingsAiPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/ai/index.tsx',
    status: 'ready',
    blocking_reason: '正式的 settings/ai 长期入口已经落地，覆盖 provider 管理、能力路由、首位管家补建与 Agent 配置中心，并复用共享 AI provider / route / agent API。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-notifications',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/index.tsx',
    status: 'in_progress',
    blocking_reason: 'H5 已覆盖免打扰开关和时段这些真实字段，但没有独立通知页；旧页里的通知方式和范围本身也主要是占位说明。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-accessibility',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/index.tsx',
    status: 'ready',
    blocking_reason: '长辈友好模式本质上是主题切换，H5 设置页已经具备对应能力；现在缺的是单独入口，不是底层实现。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-integrations',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/integrations/index.tsx',
    status: 'ready',
    blocking_reason: 'settings/integrations 已落地到 user-app，覆盖 Home Assistant 配置、设备同步、房间同步与语音终端发现/认领，只消费已有后端能力并保留可运行边界。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-channel-access',
    legacy_entry: 'apps/user-web/src/pages/SettingsChannelAccessPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/channel-access/index.tsx',
    status: 'ready',
    blocking_reason: 'settings/channel-access 已落地到 user-app，覆盖平台账号列表、新增/编辑、状态探测、启用/停用、失败记录与成员绑定，并保持家庭切换后的刷新一致性。',
    owner: 'spec011',
  },
  {
    feature_key: 'plugins',
    legacy_entry: 'apps/user-web/src/pages/SettingsPluginsPage.tsx',
    new_entry: 'apps/user-app/src/pages/plugins/index.tsx',
    status: 'ready',
    blocking_reason: '插件主链已迁入 user-app：共享层已补齐插件注册表 / 挂载 / 启停状态 / 最近任务模型与 API，页面已接入列表、详情、挂载、启用 / 禁用、删除挂载与家庭切换刷新。',
    owner: 'spec011',
  },
];

export const userWebParityRegistry: FeatureParityRegistry = {
  generatedAt: '2026-03-15',
  freezeRule: '迁移期 user-web 只允许阻断级缺陷修复和迁移桥接，不再承接正式新功能。',
  items: userWebPageParity,
};
