import { FeatureParityItem } from '@familyclaw/user-core';
import { FeatureParityRegistry } from './registry';

const userWebPageParity: FeatureParityItem[] = [
  {
    feature_key: 'shared-auth-runtime',
    legacy_entry: 'apps/user-web/src/state/auth.tsx',
    new_entry: 'packages/user-core/src/state/auth.ts',
    status: 'ready',
    blocking_reason: '认证清理和账号态判断已经收口到共享层，旧前端只保留页面上下文壳。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-household-runtime',
    legacy_entry: 'apps/user-web/src/state/household.tsx',
    new_entry: 'packages/user-core/src/state/household.ts',
    status: 'ready',
    blocking_reason: '家庭摘要、持久化 key 和读写 helper 已进入共享层，旧前端通过兼容桥接消费。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-setup-runtime',
    legacy_entry: 'apps/user-web/src/state/setup.tsx',
    new_entry: 'packages/user-core/src/state/setup.ts',
    status: 'ready',
    blocking_reason: 'setup status 读取 helper 已收口到共享层，旧前端兼容层只保留最薄桥接。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-theme-preferences',
    legacy_entry: 'apps/user-web/src/theme/ThemeProvider.tsx',
    new_entry: 'packages/user-core/src/state/theme.ts',
    status: 'ready',
    blocking_reason: '主题 ID、默认值和持久化规则已共享，旧前端保留自己的视觉 token 但不再重复维护偏好规则。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-locale-preferences',
    legacy_entry: 'apps/user-web/src/i18n/localeRegistry.ts',
    new_entry: 'packages/user-core/src/state/locale.ts',
    status: 'ready',
    blocking_reason: '语言目录解析、fallback 和存储 key 已共享，旧前端保留消息字典但不再复制同一套 locale 规则。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-realtime-protocol',
    legacy_entry: 'apps/user-web/src/lib/realtime.ts',
    new_entry: 'packages/user-platform/src/realtime/index.ts',
    status: 'ready',
    blocking_reason: '实时协议校验、URL 构造和浏览器 websocket client 已进入平台适配层，旧前端只保留薄包装。',
    owner: 'spec011',
  },
  {
    feature_key: 'shared-family-settings-api',
    legacy_entry: 'apps/user-web/src/lib/api.ts',
    new_entry: 'packages/user-core/src/api/create-api-client.ts',
    status: 'ready',
    blocking_reason: '首页、家庭、设置迁移会用到的核心 API 和领域模型已经抽到共享 client，旧前端本地 API 只保留高阶能力扩展。',
    owner: 'spec011',
  },
  {
    feature_key: 'login',
    legacy_entry: 'apps/user-web/src/pages/LoginPage.tsx',
    new_entry: 'apps/user-app/src/pages/login/index.tsx',
    status: 'in_progress',
    blocking_reason: '新页面骨架已建立，认证表单和错误态还未迁完。',
    owner: 'spec011',
  },
  {
    feature_key: 'setup-wizard',
    legacy_entry: 'apps/user-web/src/pages/SetupWizardPage.tsx',
    new_entry: 'apps/user-app/src/pages/setup/index.tsx',
    status: 'in_progress',
    blocking_reason: '只完成了占位壳，向导步骤和提交逻辑尚未迁移。',
    owner: 'spec011',
  },
  {
    feature_key: 'home',
    legacy_entry: 'apps/user-web/src/pages/HomePage.tsx',
    new_entry: 'apps/user-app/src/pages/home/index.tsx',
    status: 'in_progress',
    blocking_reason: '首页目前只接了启动摘要，业务卡片未迁入。',
    owner: 'spec011',
  },
  {
    feature_key: 'home-dashboard-shared-models',
    legacy_entry: 'apps/user-web/src/pages/HomePage.tsx',
    new_entry: 'packages/user-core/src/api/create-api-client.ts',
    status: 'ready',
    blocking_reason: '首页仪表盘依赖的 `ContextOverviewRead`、提醒总览和设备/成员/房间模型已共享，后续只差页面装配。',
    owner: 'spec011',
  },
  {
    feature_key: 'family',
    legacy_entry: 'apps/user-web/src/pages/FamilyPage.tsx',
    new_entry: 'apps/user-app/src/pages/family/index.tsx',
    status: 'in_progress',
    blocking_reason: '家庭页页面壳还没迁，但房间/成员/关系/上下文配置的共享类型和 API 已经抽好。',
    owner: 'spec011',
  },
  {
    feature_key: 'family-domain-models',
    legacy_entry: 'apps/user-web/src/pages/FamilyPage.tsx',
    new_entry: 'packages/user-core/src/domain/types.ts',
    status: 'ready',
    blocking_reason: '家庭页依赖的房间、成员、关系、偏好和上下文读模型已进入共享层。',
    owner: 'spec011',
  },
  {
    feature_key: 'assistant',
    legacy_entry: 'apps/user-web/src/pages/AssistantPage.tsx',
    new_entry: 'apps/user-app/src/pages/assistant/index.tsx',
    status: 'in_progress',
    blocking_reason: '助手页 UI 还没迁，但实时协议和 websocket client 已经从 user-web 拆到共享平台层。',
    owner: 'spec011',
  },
  {
    feature_key: 'memories',
    legacy_entry: 'apps/user-web/src/pages/MemoriesPage.tsx',
    new_entry: 'apps/user-app/src/pages/memories/index.tsx',
    status: 'not_started',
    blocking_reason: '记忆模块还没有共享视图模型。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/index.tsx',
    status: 'in_progress',
    blocking_reason: '设置总入口已接入共享主题和语言偏好，但通知、插件和更多子页还没有迁移。',
    owner: 'spec011',
  },
  {
    feature_key: 'settings-theme-language',
    legacy_entry: 'apps/user-web/src/pages/SettingsPage.tsx',
    new_entry: 'apps/user-app/src/pages/settings/index.tsx',
    status: 'ready',
    blocking_reason: '主题与语言偏好已经在新应用设置页落地，并直接使用共享偏好模型。',
    owner: 'spec011',
  },
  {
    feature_key: 'plugins',
    legacy_entry: 'apps/user-web/src/pages/SettingsPluginsPage.tsx',
    new_entry: 'apps/user-app/src/pages/plugins/index.tsx',
    status: 'not_started',
    blocking_reason: '插件管理依赖更多后端与表单逻辑，暂未开始。',
    owner: 'spec011',
  },
];

export const userWebParityRegistry: FeatureParityRegistry = {
  generatedAt: '2026-03-15',
  freezeRule: '迁移期 user-web 只允许阻断级缺陷修复和迁移桥接，不再承接正式新功能。',
  items: userWebPageParity,
};
