import type { BuiltinThemeBundleEntry } from './types';

// Auto-generated by scripts/sync-builtin-theme-plugins.mjs. Do not edit manually.
export const builtinThemeBundleIndex: BuiltinThemeBundleEntry[] = [
  {
    plugin_id: "builtin.theme.chun-he-jing-ming",
    theme_id: "chun-he-jing-ming",
    display_name: "春和景明",
    description: "温暖宁静，适合日常使用",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#d97756",
  "preview_surface": "#f7f5f2",
  "emoji": "🌸"
},
    bundle_module: "./bundles/builtin.theme.chun-he-jing-ming/chun-he-jing-ming",
    load_bundle: () => import("./bundles/builtin.theme.chun-he-jing-ming/chun-he-jing-ming").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.feng-chi-dian-che",
    theme_id: "feng-chi-dian-che",
    display_name: "风驰电掣",
    description: "霓虹电网，赛博激光",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#22d3ee",
  "preview_surface": "#160a22",
  "emoji": "⚡"
},
    bundle_module: "./bundles/builtin.theme.feng-chi-dian-che/feng-chi-dian-che",
    load_bundle: () => import("./bundles/builtin.theme.feng-chi-dian-che/feng-chi-dian-che").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.jin-xiu-qian-cheng",
    theme_id: "jin-xiu-qian-cheng",
    display_name: "锦绣前程",
    description: "鎏金尊贵，大气庄重",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#d4af37",
  "preview_surface": "#0e0c08",
  "emoji": "👑"
},
    bundle_module: "./bundles/builtin.theme.jin-xiu-qian-cheng/jin-xiu-qian-cheng",
    load_bundle: () => import("./bundles/builtin.theme.jin-xiu-qian-cheng/jin-xiu-qian-cheng").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.ming-cha-qiu-hao",
    theme_id: "ming-cha-qiu-hao",
    display_name: "明察秋毫",
    description: "更大字号、更高对比度",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#b7791f",
  "preview_surface": "#f5f5f0",
  "emoji": "🔍"
},
    bundle_module: "./bundles/builtin.theme.ming-cha-qiu-hao/ming-cha-qiu-hao",
    load_bundle: () => import("./bundles/builtin.theme.ming-cha-qiu-hao/ming-cha-qiu-hao").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.qing-shan-lv-shui",
    theme_id: "qing-shan-lv-shui",
    display_name: "青山绿水",
    description: "自然清新，森林氧吧",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#34d399",
  "preview_surface": "#f2f7f3",
  "emoji": "🌿"
},
    bundle_module: "./bundles/builtin.theme.qing-shan-lv-shui/qing-shan-lv-shui",
    load_bundle: () => import("./bundles/builtin.theme.qing-shan-lv-shui/qing-shan-lv-shui").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.wan-zi-qian-hong",
    theme_id: "wan-zi-qian-hong",
    display_name: "万紫千红",
    description: "鲜艳活泼，色彩绚烂",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#e879f9",
  "preview_surface": "#fef8ff",
  "emoji": "🌈"
},
    bundle_module: "./bundles/builtin.theme.wan-zi-qian-hong/wan-zi-qian-hong",
    load_bundle: () => import("./bundles/builtin.theme.wan-zi-qian-hong/wan-zi-qian-hong").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.xing-he-wan-li",
    theme_id: "xing-he-wan-li",
    display_name: "星河万里",
    description: "星云流动，宇宙漫游",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#60a5fa",
  "preview_surface": "#0f1228",
  "emoji": "🚀"
},
    bundle_module: "./bundles/builtin.theme.xing-he-wan-li/xing-he-wan-li",
    load_bundle: () => import("./bundles/builtin.theme.xing-he-wan-li/xing-he-wan-li").then(module => module.default),
  },
  {
    plugin_id: "builtin.theme.yue-lang-xing-xi",
    theme_id: "yue-lang-xing-xi",
    display_name: "月朗星稀",
    description: "柔和深色，减少视觉疲劳",
    source_type: 'builtin',
    resource_source: 'builtin_bundle',
    resource_version: "1.0.0",
    theme_schema_version: 1,
    platform_targets: [
  "h5",
  "rn"
],
    preview: {
  "accent_color": "#7c8cff",
  "preview_surface": "#0f1117",
  "emoji": "🌙"
},
    bundle_module: "./bundles/builtin.theme.yue-lang-xing-xi/yue-lang-xing-xi",
    load_bundle: () => import("./bundles/builtin.theme.yue-lang-xing-xi/yue-lang-xing-xi").then(module => module.default),
  },
];
